source 'https://rubygems.org'

ruby '2.3.4'

gem 'active_data', git: 'https://github.com/pyromaniac/active_data'
gem 'active_model_serializers'
gem 'acts-as-taggable-on', git: 'https://github.com/mbleigh/acts-as-taggable-on'
gem 'autoprefixer-rails'
gem 'aylien_text_api'
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'
gem 'bootstrap-daterangepicker-rails'
gem 'certified'
gem 'coffee-rails'
gem 'daemons'
gem 'elasticsearch'
gem 'faraday'
gem 'filterrific', git: 'https://github.com/ayaman/filterrific'
gem 'font-awesome-sass'
gem 'httparty'
gem 'jbuilder', '~> 2.0'
gem 'jquery-datatables-rails', '~> 3.4.0'
gem 'jquery-rails', git: 'https://github.com/rails/jquery-rails'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'listen', '~> 3.0.5'
gem 'material_icons'
gem 'momentjs-rails'
gem 'nokogiri'
gem 'omniauth-google-oauth2', '~> 0.2.1'
gem 'open_calais'
gem 'open_uri_redirections'
gem 'paperclip', '~> 5.0.0'
gem 'pg', '~> 0.19'
gem 'rails', '5.1.1'
gem 'react-rails', git: 'https://github.com/reactjs/react-rails'
gem 'rest-client'
gem 'sass-rails'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'searchkick'
gem 'select2-rails'
gem 'sprockets-rails', '2.3.3'
gem 'tether-rails'
gem 'titleize'
gem 'turbolinks'
gem 'twitter', git: 'https://github.com/sferik/twitter'
gem 'typhoeus'
gem 'uglifier'
gem 'unshorten'
gem 'webpacker'
gem 'whenever', :require => false

group :development, :test do
  gem 'faker'
  gem 'pry'
end

group :development do
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console'
end
